name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test
      run: go test ./...
